language: clojure
lein: lein2
before_script:
- psql -c 'create database "staircase-test";' -U postgres
jdk:
- oraclejdk8
- openjdk7
- oraclejdk7
- openjdk6
install:
- lein2 with-profile dev,travis deps # Server side deps
- npm install # Client side deps
script:
- lein2 with-profile dev,travis do pprint :env, test
- npm test
