language: clojure
lein: lein2
before_script:
    - psql -c 'create database "staircase-test";' -U postgres
jdk:
    - openjdk7
    - oraclejdk7
    - openjdk6
install: lein2 with-profile dev,travis deps
script: lein2 with-profile dev,travis do pprint :env, test
