language: clojure
lein: lein2
before_script:
- psql -c 'create database "staircase-test";' -U postgres
jdk:
- oraclejdk8
- openjdk7
- oraclejdk7
- openjdk6
install: lein2 with-profile dev,travis deps
script: lein2 with-profile dev,travis do pprint :env, test
deploy:
  provider: heroku
  buildpack: "https://github.com/ddollar/heroku-buildpack-multi.git"
  strategy: git
  api_key:
    secure: EPS19rvOFf4Vh2YODFrvLCKnhqSFk/tKfY1xwxpYAVA/QXgKnBF3iGQ7Z31T/+0XZryHsGA4ZlcWqpXh71GB8n63nd00X6gdaHIIMKX+gqskIJo1Hell6UVR+qypYpdxkeg9tFsIu3XOj7dTSHlE5aXZYsxcYegIyFyVALgvMT0=
  app: staircase-staging
  on:
    branch: master
    repo: alexkalderimis/staircase
    jdk: openjdk7
